In [1]:
#importing the libraries we need to use for data analysis

import pandas as pd
import numpy as np
print("All good")

All good

In [2]:
#load the data set into the data frame(allows us to start exploring for potential data cleanups)
df = pd.read_csv("ai_productivity_dataset_final.csv")

# first 5 rows to get a gist of what the data looks like
df.head()

,task_id,client,project_id,client_tier,team,task_type,seniority,task_complexity_score,brief_quality_score,deadline_pressure,...,revenue,cost,profit,created_by,updated_at,task_status,workflow_stage,jira_ticket,legacy_ai_flag,content_version
0,T00000,Client_F,P038,mid,Content,report,junior,2,3.0,high,...,498.11,346.17,151.94,user_096,2025-11-28,review,finalized,JIRA-49014,true,v1
1,T00001,Client_H,P028,low,Paid Media,release,junior,1,2.0,medium,...,847.01,343.18,503.83,user_058,2026-01-26,delivered,client_review,JIRA-84793,false,v1
2,T00002,Client_D,P009,low,Design,dev,junior,3,4.0,medium,...,1374.07,365.02,1009.05,user_074,2025-09-17,in_progress,qa,JIRA-42485,true,v2
3,T00003,Client_E,P023,mid,Content,design,mid,3,2.0,low,...,2379.11,1514.73,864.38,user_011,2025-11-12,in_progress,briefing,JIRA-53111,false,v1
4,T00004,Client_C,P014,low,Design,article,senior,2,5.0,low,...,709.95,335.27,374.68,user_007,2026-05-09,review,execution,JIRA-86006,true,v2

In [3]:
# checking the column names to see what variables we are working with
print("Columns:", df.columns)

# getting general information about the dataset to check for missing values
df.info()

#rows and columns
print("Shape:", df.shape)

Columns: Index(['task_id', 'client', 'project_id', 'client_tier', 'team', 'task_type',
       'seniority', 'task_complexity_score', 'brief_quality_score',
       'deadline_pressure', 'scope_change_flag', 'pricing_model', 'created_at',
       'delivered_at', 'sla_days', 'sla_breach', 'hours_spent',
       'billable_hours', 'ai_usage_pct', 'ai_assisted', 'revisions', 'errors',
       'rework_hours', 'outcome_score', 'revenue', 'cost', 'profit',
       'created_by', 'updated_at', 'task_status', 'workflow_stage',
       'jira_ticket', 'legacy_ai_flag', 'content_version'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 3248 entries, 0 to 3247
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   task_id                3248 non-null   str
 1   client                 3248 non-null   str
 2   project_id             3248 non-null   str
 3   client_tier            3248 non-null   str
 4   team                   3248 non-null   str
 5   task_type              3248 non-null   str
 6   seniority              3248 non-null   str
 7   task_complexity_score  3248 non-null   int64
 8   brief_quality_score    3179 non-null   float64
 9   deadline_pressure      3248 non-null   str
 10  scope_change_flag      3248 non-null   int64
 11  pricing_model          3248 non-null   str
 12  created_at             3248 non-null   str
 13  delivered_at           3210 non-null   str
 14  sla_days               3212 non-null   float64
 15  sla_breach             3248 non-null   int64
 16  hours_spent            3248 non-null   float64
 17  billable_hours         3166 non-null   float64
 18  ai_usage_pct           3104 non-null   float64
 19  ai_assisted            3248 non-null   bool
 20  revisions              3248 non-null   int64
 21  errors                 3248 non-null   int64
 22  rework_hours           3176 non-null   float64
 23  outcome_score          3115 non-null   float64
 24  revenue                3248 non-null   float64
 25  cost                   3248 non-null   float64
 26  profit                 3248 non-null   float64
 27  created_by             3248 non-null   str
 28  updated_at             3248 non-null   str
 29  task_status            3248 non-null   str
 30  workflow_stage         3248 non-null   str
 31  jira_ticket            2909 non-null   str
 32  legacy_ai_flag         3248 non-null   str
 33  content_version        3248 non-null   str
dtypes: bool(1), float64(10), int64(5), str(18)
memory usage: 840.7 KB
Shape: (3248, 34)

In [4]:
#so we don't accidentally chenge the original dataset
df_clean = df.copy()

In [5]:
# checking how many missing values are in each column to determine how we can go aboutt the cleaning
print(df_clean.isnull().sum())

task_id                    0
client                     0
project_id                 0
client_tier                0
team                       0
task_type                  0
seniority                  0
task_complexity_score      0
brief_quality_score       69
deadline_pressure          0
scope_change_flag          0
pricing_model              0
created_at                 0
delivered_at              38
sla_days                  36
sla_breach                 0
hours_spent                0
billable_hours            82
ai_usage_pct             144
ai_assisted                0
revisions                  0
errors                     0
rework_hours              72
outcome_score            133
revenue                    0
cost                       0
profit                     0
created_by                 0
updated_at                 0
task_status                0
workflow_stage             0
jira_ticket              339
legacy_ai_flag             0
content_version            0
dtype: int64

In [6]:
#check for duplicate values
print("Duplicate rows:", df_clean.duplicated().sum())

Duplicate rows: 0

In [7]:
#summary of all columns(numerical & categorical);to understand general patterns in the dataa
df_clean.describe(include='all')

,task_id,client,project_id,client_tier,team,task_type,seniority,task_complexity_score,brief_quality_score,deadline_pressure,...,revenue,cost,profit,created_by,updated_at,task_status,workflow_stage,jira_ticket,legacy_ai_flag,content_version
count,3248,3248,3248,3248,3248,3248,3248,3248.000000,3179.000000,3248,...,3248.000000,3248.000000,3248.000000,3248,3248,3248,3248,2909,3248,3248
unique,3200,28,64,3,15,29,3,NaN,NaN,3,...,NaN,NaN,NaN,119,338,6,5,2868,3,5
top,T00010,Client_G,P028,mid,Content,design,mid,NaN,NaN,medium,...,NaN,NaN,NaN,user_026,2026-03-01,in_progress,qa,JIRA-53111,false,v1
freq,2,415,77,1514,803,456,1296,NaN,NaN,1482,...,NaN,NaN,NaN,44,20,1129,687,2,1458,926
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.868842,3.183391,NaN,...,1120.571260,771.308146,349.263114,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.196459,1.211712,NaN,...,841.649433,584.269354,888.072715,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,...,45.000000,77.850000,-8510.549511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,NaN,...,646.312500,440.805000,-2.610000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,3.000000,NaN,...,966.430000,649.065000,254.645000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,4.000000,NaN,...,1364.700000,941.145000,590.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,5.000000,NaN,...,14927.204324,9409.639511,14006.644324,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#remove extra spaces and make lowercase
df_clean.columns = df_clean.columns.str.strip().str.lower()
print(df_clean.columns)

Index(['task_id', 'client', 'project_id', 'client_tier', 'team', 'task_type',
       'seniority', 'task_complexity_score', 'brief_quality_score',
       'deadline_pressure', 'scope_change_flag', 'pricing_model', 'created_at',
       'delivered_at', 'sla_days', 'sla_breach', 'hours_spent',
       'billable_hours', 'ai_usage_pct', 'ai_assisted', 'revisions', 'errors',
       'rework_hours', 'outcome_score', 'revenue', 'cost', 'profit',
       'created_by', 'updated_at', 'task_status', 'workflow_stage',
       'jira_ticket', 'legacy_ai_flag', 'content_version'],
      dtype='str')

In [9]:
#remove rows with missing values
df_clean = df_clean.dropna()

In [10]:
#remove duplicate rows(if any)
df_clean = df_clean.drop_duplicates()

In [11]:
#checking final shape after cleaning
print("Final shape:", df_clean.shape)
#make sure there arnet missing values left
print(df_clean.isnull().sum())
#confirm no remaining duplicate rows
print("Duplicate rows after cleaning:", df_clean.duplicated().sum())

Final shape: (2431, 34)
task_id                  0
client                   0
project_id               0
client_tier              0
team                     0
task_type                0
seniority                0
task_complexity_score    0
brief_quality_score      0
deadline_pressure        0
scope_change_flag        0
pricing_model            0
created_at               0
delivered_at             0
sla_days                 0
sla_breach               0
hours_spent              0
billable_hours           0
ai_usage_pct             0
ai_assisted              0
revisions                0
errors                   0
rework_hours             0
outcome_score            0
revenue                  0
cost                     0
profit                   0
created_by               0
updated_at               0
task_status              0
workflow_stage           0
jira_ticket              0
legacy_ai_flag           0
content_version          0
dtype: int64
Duplicate rows after cleaning: 0